Repository dorimedini/kardashigans, pull requests merged in 2019-08, with the labels that each got.

#78 Export results to csv
  analyze_model.py
Labels: enhancement

#87 Implement pruning in base trainer
  trainer.py
Labels: enhancement

#88 Add experiment winnery ticker layer intersection
  analyze_model.py
  winnery_intersection.py
Labels: experiment

#94 no need to save clean_results, thus avoiding the bug
  experiment.py
Labels: bug

#95 Transfer experiment
  analyze_model.py
  resource_manager.py
  trainer.py
  transfer.py
Labels: enhancement

#96 added regularizers and drop out to FCTrainer
  trainer.py
Labels: enhancement

#103 Accepted by me. For some reason unaccepted papers are authorless
  latex/main.tex
Labels: bug

#106 Heatmap constifyyyy scale color
  analyze_model.py
Labels: enhancement

#108 Measure accuracy in winnery pruned unpruned
  analyze_model.py
  winnery_intersection.py
Labels: enhancement

#110 Transfer add early stop cb
  analyze_model.py
  experiment.py
  resource_manager.py
  trainer.py
  transfer.py
Labels: enhancement

#111 Added setting, training w\ frozen and robustness w\ frozen sections, with images directory.
  latex/images/baseline_fc3_mnist_heatmap.png
  latex/images/f12_fc3_mnist_heatmap.png
  latex/images/fc3_mnist_drop_in_acc_by_layer.png
  latex/images/fc3_mnist_l2_reg.png
  latex/images/fc3_mnist_l2_reg_drop_in_acc_by_layer.png
  latex/images/fc3_mnist_training_plots.png
  latex/images/fc5_mnist_drop_in_acc_by_layer.png
  latex/main.tex
Labels: documentation
