Repository dorimedini/kardashigans, pull requests merged in 2019-07, with the labels that each got.

#30 resource_load_dir is given relative to root_dir
  experiment.py
Labels: bug

#31 added rernd to calc robustness
  experiment.py
Labels: enhancement

#36 Now log with timestamp
  experiment.py
  resource_manager.py
  trainer.py
  verbose.py
Labels: enhancement

#34 Allow add callbacks to trainer
  experiment.py
  resource_manager.py
  trainer.py
Labels: bug, enhancement

#42 n_layers given to trainer is now the number of hidden layers (excludi…
  trainer.py
Labels: bug

#45 Baseline now correctly shows 4 parameter layers in phase 2
  baseline.py
Labels: bug

#43 Load model on demand
  baseline.py
  experiment.py
  resource_manager.py
Labels: enhancement

#51 Epoch checkpoints should be specific
  baseline.py
  experiment.py
  resource_manager.py
Labels: enhancement

#54 Fixed issue with epoch 0 loading baseline model
  experiment.py
Labels: bug

#53 Open base model in phase2() once, then each epoch in _phase2_dataset.…
  baseline.py
Labels: enhancement

#63 Baseline wasn't analyzing enough parameter layers
  baseline.py
Labels: bug

#58 Kill verbose
  analyze_model.py
  baseline.py
  baseline_runner.py
  experiment.py
  resource_manager.py
  trainer.py
  verbose.py
Labels: enhancement

#65 calc_robustness changes
  analyze_model.py
  experiment.py
Labels: enhancement

#69 Now the formatter is timezone-aware
  verbose.py
Labels: enhancement

#70 ResourceManager now tells us when load is successful in the end
  resource_manager.py
Labels: enhancement

#68 Add experiment robustness by epoch
  analyze_model.py
  baseline.py
  experiment.py
  resource_manager.py
  simple_experiment.py
  trainer.py
Labels: experiment

#72 Resource manager should output eval results
  experiment.py
  resource_manager.py
  simple_experiment.py
Labels: enhancement

#80 Add VGG trainer
  baseline.py
  experiment.py
  simple_experiment.py
  trainer.py
Labels: enhancement
